- name: installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest
- name: enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
- name: run common pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: copy backend conf
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
