- name: pinging the server -y
  hosts: db
  tasks:
    - name: pinging the server 
      ansible.builtin.ping:
      register: ping_result

    - name: Status of servers
      ansible.builtin.debug:
        msg: "{{ ping_result }}"
