- name: Pinging the DB server
  hosts: db
  tasks:
    - name: Ping the server
      ansible.builtin.ping:
      register: ping_result

    - name: Status of servers
      ansible.builtin.debug:
        msg: "{{ ping_result }}"
