- name: loops
  hosts: localhost
  tasks:
    - name: looping throught list of items
      ansible.builtin.debug:
       msg: "item :: {{item}}"
      loop: 
        -linux
        -shell
        -ansible