- name: loops
  hosts: localhost
  tasks:
    - name: Looping through list of items
      ansible.builtin.debug:
      msg: "Item :: {{ item }}"
      loop: 
        - linux
        - shell
        - ansible